name: CI/CD Pipeline for Dockerized Spring App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка JDK
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Шаг 3: Сборка проекта с Maven
      - name: Build with Maven
        run: mvn clean package

      # Шаг 4: Запуск тестов
      - name: Run tests
        run: mvn test

      # Шаг 5: Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t my-spring-app .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Деплой через SSH на удаленный сервер
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
            docker stop my-spring-app || true
            docker rm my-spring-app || true
            docker run -d -p 8080:8080 --name my-spring-app ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
